/**
 * The component catalog, typed for the browser.
 *
 * `catalog.json` is generated by `scripts/generate-agent-catalog.mjs` from the
 * same three sources the backend uses (the public component metadata, the
 * measured pin map and the wiring rule file), so the agent in the browser and
 * the agent on the server can never disagree about which parts exist, what
 * their pins are called, or which properties a patch may touch.
 *
 * Nothing here is hand-maintained per part. When a new component is added to
 * the canvas, it appears here as soon as the generator runs — which is also
 * what the pin-drift test in `src/agent/__tests__/catalog.test.ts` enforces.
 */
import raw from './catalog.json';

export interface PinVariant {
  when: Record<string, string>;
  pins: string[];
}

export interface SignalRule {
  cap: string;
  dir?: 'in' | 'out' | 'bidir';
  optional?: boolean;
  severity?: string;
}

export interface BusRule {
  type: string;
  pins: Record<string, string>;
  optional?: boolean;
  when?: Record<string, string>;
}

export interface PartSpec {
  name: string;
  tag: string;
  category: string;
  class: string;
  pins: string[];
  pinVariants?: PinVariant[];
  properties: string[];
  defaults: Record<string, string | number | boolean>;
  placeable: boolean;
  sim: boolean;
  tags: string[];
  description?: string;
  why?: string;
  notes?: string;
  power?: Record<string, 'supply' | 'ground'>;
  signal?: Record<string, SignalRule>;
  bus?: BusRule[];
  libraries?: string[];
  interactions?: string[];
  stimulusKeys?: string[];
  [key: string]: unknown;
}

export interface BoardSpec {
  label: string;
  fqbn: string | null;
  kind: string;
  family?: string;
  pins: string[];
  pwm: number[];
  analog: string[];
  serial: string[];
  i2c: Record<string, string>;
  spi: Record<string, string>;
  uart: Record<string, string>;
  vcc: number;
  max_pin_ma: number;
}

interface CatalogFile {
  version: number;
  boards: Record<string, BoardSpec>;
  boardCoreHeaders?: Record<string, string[]>;
  boardCoreHeadersByBoard?: Record<string, string[]>;
  severity: Record<string, string>;
  runtimeProperties: { global: string[]; parts: Record<string, string[]> };
  parts: Record<string, PartSpec>;
}

export const catalog = raw as unknown as CatalogFile;
export const PARTS: Record<string, PartSpec> = catalog.parts;
export const BOARD: BoardSpec = catalog.boards['arduino-uno'];

const BOARD_ALIASES: Record<string, string> = {
  uno: 'arduino-uno',
  nano: 'arduino-nano',
  mega: 'arduino-mega',
  esp32dev: 'esp32',
  'esp32-devkit': 'esp32',
  pico: 'raspberry-pi-pico',
  rp2040: 'raspberry-pi-pico',
  picow: 'pi-pico-w',
  'pico-w': 'pi-pico-w',
};

/** Canonical board kind shared with backend Board normalization. */
export function normalizeBoardKind(value: string | undefined): string | undefined {
  if (!value) return undefined;
  if (Object.prototype.hasOwnProperty.call(catalog.boards, value)) return value;
  return BOARD_ALIASES[value.toLowerCase()];
}

/** Every part a patch may place, sorted by id. */
export const PLACEABLE_IDS: string[] = Object.entries(PARTS)
  .filter(([, spec]) => spec.placeable)
  .map(([id]) => id)
  .sort();

/** Total parts the canvas knows about (placeable or not). */
export const CATALOG_SIZE = Object.keys(PARTS).length;
export const PLACEABLE_SIZE = PLACEABLE_IDS.length;

const RUNTIME_GLOBAL = new Set(catalog.runtimeProperties.global);

export function partSpec(id: string): PartSpec | undefined {
  return PARTS[id];
}

export function isPlaceable(id: string): boolean {
  return PARTS[id]?.placeable === true;
}

/** Properties a patch may set — the catalog's editable list for the part. */
export function editableProperties(id: string): string[] {
  return PARTS[id]?.properties ?? [];
}

/** Properties the canvas owns at runtime and a patch must never set. */
export function runtimePropertiesFor(id: string): Set<string> {
  return new Set([...RUNTIME_GLOBAL, ...(catalog.runtimeProperties.parts[id] ?? [])]);
}

/** Pins for an instance, honouring property-driven variants (digits=4, pins=i2c). */
export function pinsFor(id: string, properties: Record<string, unknown> = {}): string[] {
  const spec = PARTS[id];
  if (!spec) return [];
  for (const variant of spec.pinVariants ?? []) {
    const matches = Object.entries(variant.when).every(
      ([key, value]) => String(properties[key] ?? '') === String(value),
    );
    if (matches) return variant.pins;
  }
  return spec.pins;
}

/** Interactions the runtime can actually drive for this part. */
export function interactionsFor(id: string): string[] {
  return PARTS[id]?.interactions ?? [];
}
